spring:
  application:
    name: @project.artifactId@
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:jobsposted}
    username: ${POSTGRES_USER:jobsposteduser}
    password: ${POSTGRES_PASSWORD:jobspostedpwd}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
    clear-checksums: true
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER:root}:${MONGODB_PASSWORD:example}@localhost:27017/admin
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: ${NEO4J_USER:neo4j}
      password: ${NEO4J_PASSWORD:password}

server:
  port: 8085
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

jwt:
  secret: ${JWT_SECRET:4t2OcI9neLkUD+WPsQuAxpjzT6BFQHMc/JNaiAyCFNQIyWAsSGauuxZzV9Hxgc+G8+OqlK3hIaTjRrKSxLoRbw==}
  expiration: 604800

management:
  endpoints:
    web:
      exposure:
        include: health,info

resilience4j.circuitbreaker:
  instances:
    applicantService:
      registerHealthIndicator: true
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 10
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
